import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcrypt';
import { User } from '../modules/user/user.model';

// Load environment variables
dotenv.config();

// Function to drop the entire database
const dropDatabase = async () => {
  try {
    await mongoose.connection.dropDatabase();
    console.log('------------> Database dropped successfully! <------------');
  } catch (err) {
    console.error('Error dropping database:', err);
  }
};

// Function to hash password
const hashPassword = async (password: string) => {
  const salt = await bcrypt.genSalt(10);
  return await bcrypt.hash(password, salt);
};

// Function to seed users
const seedUsers = async () => {
  try {
    const usersData = [
      {
        firstName: 'Shannon ',
        lastName: 'Lawrence',
        email: 'iterbeneadmin@iterbene.com',
        username: 'iterbeneadmin',
        phoneNumber: '+12025550120',
        password: '1qazxsw2',
        role: 'Admin',
      },
      {
        firstName: 'John',
        lastName: 'Doe',
        username: 'johndoe1',
        nickname: 'Johnny',
        email: 'john.doe1@example.com',
        password: 'password123',
        phoneNumber: '123-456-7890',
        status: 'Active',
        location: { latitude: 40.7128, longitude: -74.006 },
        locationName: 'New York',
        address: '123 Main St',
        gender: 'Male',
        maritalStatus: 'Single',
        description: 'Loves tech and coding',
        role: 'User',
        profession: 'Developer',
        ageRange: '25-30',
        country: 'USA',
        city: 'New York',
        state: 'NY',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Jane',
        lastName: 'Smith',
        username: 'janesmith2',
        nickname: 'Janey',
        email: 'jane.smith2@example.com',
        password: 'password123',
        phoneNumber: '234-567-8901',
        status: 'Active',
        location: { latitude: 34.0522, longitude: -118.2437 },
        locationName: 'Los Angeles',
        address: '456 Oak St',
        gender: 'Female',
        maritalStatus: 'Married',
        description: 'Enjoys hiking',
        role: 'User',
        profession: 'Designer',
        ageRange: '30-35',
        country: 'USA',
        city: 'Los Angeles',
        state: 'CA',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Michael',
        lastName: 'Johnson',
        username: 'michaelj3',
        nickname: 'Mike',
        email: 'michael.johnson3@example.com',
        password: 'password123',
        phoneNumber: '345-678-9012',
        status: 'Active',
        location: { latitude: 51.5074, longitude: -0.1278 },
        locationName: 'London',
        address: '789 Pine St',
        gender: 'Male',
        maritalStatus: 'Single',
        description: 'Tech enthusiast',
        role: 'Admin',
        profession: 'Engineer',
        ageRange: '35-40',
        country: 'UK',
        city: 'London',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Emily',
        lastName: 'Brown',
        username: 'emilyb4',
        nickname: 'Em',
        email: 'emily.brown4@example.com',
        password: 'password123',
        phoneNumber: '456-789-0123',
        status: 'Active',
        location: { latitude: 48.8566, longitude: 2.3522 },
        locationName: 'Paris',
        address: '101 Elm St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Art lover',
        role: 'User',
        profession: 'Artist',
        ageRange: '20-25',
        country: 'France',
        city: 'Paris',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'David',
        lastName: 'Wilson',
        username: 'davidw5',
        nickname: 'Dave',
        email: 'david.wilson5@example.com',
        password: 'password123',
        phoneNumber: '567-890-1234',
        status: 'Active',
        location: { latitude: 35.6762, longitude: 139.6503 },
        locationName: 'Tokyo',
        address: '202 Maple St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Travel enthusiast',
        role: 'User',
        profession: 'Tour Guide',
        ageRange: '40-45',
        country: 'Japan',
        city: 'Tokyo',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Sarah',
        lastName: 'Davis',
        username: 'sarahd6',
        nickname: 'Sara',
        email: 'sarah.davis6@example.com',
        password: 'password123',
        phoneNumber: '678-901-2345',
        status: 'Active',
        location: { latitude: 37.7749, longitude: -122.4194 },
        locationName: 'San Francisco',
        address: '303 Birch St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Coffee addict',
        role: 'User',
        profession: 'Barista',
        ageRange: '25-30',
        country: 'USA',
        city: 'San Francisco',
        state: 'CA',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Robert',
        lastName: 'Taylor',
        username: 'robertt7',
        nickname: 'Rob',
        email: 'robert.taylor7@example.com',
        password: 'password123',
        phoneNumber: '789-012-3456',
        status: 'Active',
        location: { latitude: 52.52, longitude: 13.405 },
        locationName: 'Berlin',
        address: '404 Cedar St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'History buff',
        role: 'User',
        profession: 'Historian',
        ageRange: '45-50',
        country: 'Germany',
        city: 'Berlin',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Lisa',
        lastName: 'Anderson',
        username: 'lisaa8',
        nickname: 'Liz',
        email: 'lisa.anderson8@example.com',
        password: 'password123',
        phoneNumber: '890-123-4567',
        status: 'Active',
        location: { latitude: 55.7558, longitude: 37.6173 },
        locationName: 'Moscow',
        address: '505 Oak St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Music lover',
        role: 'User',
        profession: 'Musician',
        ageRange: '30-35',
        country: 'Russia',
        city: 'Moscow',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'James',
        lastName: 'Martinez',
        username: 'jamesm9',
        nickname: 'Jim',
        email: 'james.martinez9@example.com',
        password: 'password123',
        phoneNumber: '901-234-5678',
        status: 'Active',
        location: { latitude: -33.8688, longitude: 151.2093 },
        locationName: 'Sydney',
        address: '606 Pine St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Beach lover',
        role: 'User',
        profession: 'Lifeguard',
        ageRange: '35-40',
        country: 'Australia',
        city: 'Sydney',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Mary',
        lastName: 'Garcia',
        username: 'maryg10',
        nickname: 'Maria',
        email: 'mary.garcia10@example.com',
        password: 'password123',
        phoneNumber: '012-345-6789',
        status: 'Active',
        location: { latitude: 19.4326, longitude: -99.1332 },
        locationName: 'Mexico City',
        address: '707 Elm St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Foodie',
        role: 'User',
        profession: 'Chef',
        ageRange: '25-30',
        country: 'Mexico',
        city: 'Mexico City',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'William',
        lastName: 'Lopez',
        username: 'williaml11',
        nickname: 'Will',
        email: 'william.lopez11@example.com',
        password: 'password123',
        phoneNumber: '123-456-7891',
        status: 'Active',
        location: { latitude: 40.7128, longitude: -74.006 },
        locationName: 'New York',
        address: '808 Maple St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Sports fan',
        role: 'User',
        profession: 'Athlete',
        ageRange: '40-45',
        country: 'USA',
        city: 'New York',
        state: 'NY',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Patricia',
        lastName: 'Hernandez',
        username: 'patriciah12',
        nickname: 'Pat',
        email: 'patricia.hernandez12@example.com',
        password: 'password123',
        phoneNumber: '234-567-8902',
        status: 'Active',
        location: { latitude: 34.0522, longitude: -118.2437 },
        locationName: 'Los Angeles',
        address: '909 Birch St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Nature lover',
        role: 'User',
        profession: 'Botanist',
        ageRange: '30-35',
        country: 'USA',
        city: 'Los Angeles',
        state: 'CA',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Thomas',
        lastName: 'Gonzalez',
        username: 'thomasg13',
        nickname: 'Tom',
        email: 'thomas.gonzalez13@example.com',
        password: 'password123',
        phoneNumber: '345-678-9013',
        status: 'Active',
        location: { latitude: 51.5074, longitude: -0.1278 },
        locationName: 'London',
        address: '1010 Cedar St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Bookworm',
        role: 'User',
        profession: 'Librarian',
        ageRange: '45-50',
        country: 'UK',
        city: 'London',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Jennifer',
        lastName: 'Perez',
        username: 'jenniferp14',
        nickname: 'Jen',
        email: 'jennifer.perez14@example.com',
        password: 'password123',
        phoneNumber: '456-789-0124',
        status: 'Active',
        location: { latitude: 48.8566, longitude: 2.3522 },
        locationName: 'Paris',
        address: '1111 Elm St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Fashionista',
        role: 'User',
        profession: 'Designer',
        ageRange: '20-25',
        country: 'France',
        city: 'Paris',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Charles',
        lastName: 'Ramirez',
        username: 'charlesr15',
        nickname: 'Charlie',
        email: 'charles.ramirez15@example.com',
        password: 'password123',
        phoneNumber: '567-890-1235',
        status: 'Active',
        location: { latitude: 35.6762, longitude: 139.6503 },
        locationName: 'Tokyo',
        address: '1212 Maple St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Gamer',
        role: 'User',
        profession: 'Game Developer',
        ageRange: '35-40',
        country: 'Japan',
        city: 'Tokyo',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Barbara',
        lastName: 'Torres',
        username: 'barbarat16',
        nickname: 'Barb',
        email: 'barbara.torres16@example.com',
        password: 'password123',
        phoneNumber: '678-901-2346',
        status: 'Active',
        location: { latitude: 37.7749, longitude: -122.4194 },
        locationName: 'San Francisco',
        address: '1313 Birch St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Photographer',
        role: 'User',
        profession: 'Photographer',
        ageRange: '25-30',
        country: 'USA',
        city: 'San Francisco',
        state: 'CA',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Daniel',
        lastName: 'Flores',
        username: 'danielf17',
        nickname: 'Dan',
        email: 'daniel.flores17@example.com',
        password: 'password123',
        phoneNumber: '789-012-3457',
        status: 'Active',
        location: { latitude: 52.52, longitude: 13.405 },
        locationName: 'Berlin',
        address: '1414 Cedar St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Tech geek',
        role: 'User',
        profession: 'IT Specialist',
        ageRange: '40-45',
        country: 'Germany',
        city: 'Berlin',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Nancy',
        lastName: 'Rivera',
        username: 'nancyr18',
        nickname: 'Nan',
        email: 'nancy.rivera18@example.com',
        password: 'password123',
        phoneNumber: '890-123-4568',
        status: 'Active',
        location: { latitude: 55.7558, longitude: 37.6173 },
        locationName: 'Moscow',
        address: '1515 Elm St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Dancer',
        role: 'User',
        profession: 'Dancer',
        ageRange: '30-35',
        country: 'Russia',
        city: 'Moscow',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Paul',
        lastName: 'Gomez',
        username: 'paulg19',
        nickname: 'Pauly',
        email: 'paul.gomez19@example.com',
        password: 'password123',
        phoneNumber: '901-234-5679',
        status: 'Active',
        location: { latitude: -33.8688, longitude: 151.2093 },
        locationName: 'Sydney',
        address: '1616 Maple St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Surfer',
        role: 'User',
        profession: 'Surfer',
        ageRange: '35-40',
        country: 'Australia',
        city: 'Sydney',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Ruth',
        lastName: 'Diaz',
        username: 'ruthd20',
        nickname: 'Ruthie',
        email: 'ruth.diaz20@example.com',
        password: 'password123',
        phoneNumber: '012-345-6780',
        status: 'Active',
        location: { latitude: 19.4326, longitude: -99.1332 },
        locationName: 'Mexico City',
        address: '1717 Birch St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Cook',
        role: 'User',
        profession: 'Chef',
        ageRange: '25-30',
        country: 'Mexico',
        city: 'Mexico City',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'George',
        lastName: 'Cruz',
        username: 'georgec21',
        nickname: 'Geo',
        email: 'george.cruz21@example.com',
        password: 'password123',
        phoneNumber: '123-456-7892',
        status: 'Active',
        location: { latitude: 40.7128, longitude: -74.006 },
        locationName: 'New York',
        address: '1818 Cedar St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Fitness buff',
        role: 'User',
        profession: 'Trainer',
        ageRange: '40-45',
        country: 'USA',
        city: 'New York',
        state: 'NY',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Margaret',
        lastName: 'Morales',
        username: 'margaretm22',
        nickname: 'Maggie',
        email: 'margaret.morales22@example.com',
        password: 'password123',
        phoneNumber: '234-567-8903',
        status: 'Active',
        location: { latitude: 34.0522, longitude: -118.2437 },
        locationName: 'Los Angeles',
        address: '1919 Elm St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Writer',
        role: 'User',
        profession: 'Writer',
        ageRange: '30-35',
        country: 'USA',
        city: 'Los Angeles',
        state: 'CA',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Edward',
        lastName: 'Ortiz',
        username: 'edwardo23',
        nickname: 'Ed',
        email: 'edward.ortiz23@example.com',
        password: 'password123',
        phoneNumber: '345-678-9014',
        status: 'Active',
        location: { latitude: 51.5074, longitude: -0.1278 },
        locationName: 'London',
        address: '2020 Maple St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Traveler',
        role: 'User',
        profession: 'Pilot',
        ageRange: '45-50',
        country: 'UK',
        city: 'London',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Betty',
        lastName: 'Gutierrez',
        username: 'bettyg24',
        nickname: 'Bets',
        email: 'betty.gutierrez24@example.com',
        password: 'password123',
        phoneNumber: '456-789-0125',
        status: 'Active',
        location: { latitude: 48.8566, longitude: 2.3522 },
        locationName: 'Paris',
        address: '2121 Birch St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Painter',
        role: 'User',
        profession: 'Artist',
        ageRange: '20-25',
        country: 'France',
        city: 'Paris',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Ronald',
        lastName: 'Sanchez',
        username: 'ronalds25',
        nickname: 'Ron',
        email: 'ronald.sanchez25@example.com',
        password: 'password123',
        phoneNumber: '567-890-1236',
        status: 'Active',
        location: { latitude: 35.6762, longitude: 139.6503 },
        locationName: 'Tokyo',
        address: '2222 Cedar St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Gadget lover',
        role: 'User',
        profession: 'Technician',
        ageRange: '35-40',
        country: 'Japan',
        city: 'Tokyo',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Dorothy',
        lastName: 'Reyes',
        username: 'dorothyr26',
        nickname: 'Dot',
        email: 'dorothy.reyes26@example.com',
        password: 'password123',
        phoneNumber: '678-901-2347',
        status: 'Active',
        location: { latitude: 37.7749, longitude: -122.4194 },
        locationName: 'San Francisco',
        address: '2323 Elm St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Yoga instructor',
        role: 'User',
        profession: 'Instructor',
        ageRange: '25-30',
        country: 'USA',
        city: 'San Francisco',
        state: 'CA',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Kenneth',
        lastName: 'Castillo',
        username: 'kennethc27',
        nickname: 'Ken',
        email: 'kenneth.castillo27@example.com',
        password: 'password123',
        phoneNumber: '789-012-3458',
        status: 'Active',
        location: { latitude: 52.52, longitude: 13.405 },
        locationName: 'Berlin',
        address: '2424 Maple St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Cyclist',
        role: 'User',
        profession: 'Cyclist',
        ageRange: '40-45',
        country: 'Germany',
        city: 'Berlin',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Helen',
        lastName: 'Jimenez',
        username: 'helenj28',
        nickname: 'Helly',
        email: 'helen.jimenez28@example.com',
        password: 'password123',
        phoneNumber: '890-123-4569',
        status: 'Active',
        location: { latitude: 55.7558, longitude: 37.6173 },
        locationName: 'Moscow',
        address: '2525 Birch St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Singer',
        role: 'User',
        profession: 'Singer',
        ageRange: '30-35',
        country: 'Russia',
        city: 'Moscow',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Steven',
        lastName: 'Mendoza',
        username: 'stevenm29',
        nickname: 'Steve',
        email: 'steven.mendoza29@example.com',
        password: 'password123',
        phoneNumber: '901-234-5670',
        status: 'Active',
        location: { latitude: -33.8688, longitude: 151.2093 },
        locationName: 'Sydney',
        address: '2626 Cedar St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Diver',
        role: 'User',
        profession: 'Diver',
        ageRange: '35-40',
        country: 'Australia',
        city: 'Sydney',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Donna',
        lastName: 'Herrera',
        username: 'donnah30',
        nickname: 'Don',
        email: 'donna.herrera30@example.com',
        password: 'password123',
        phoneNumber: '012-345-6781',
        status: 'Active',
        location: { latitude: 19.4326, longitude: -99.1332 },
        locationName: 'Mexico City',
        address: '2727 Elm St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Baker',
        role: 'User',
        profession: 'Baker',
        ageRange: '25-30',
        country: 'Mexico',
        city: 'Mexico City',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Richard',
        lastName: 'Medina',
        username: 'richardm31',
        nickname: 'Rich',
        email: 'richard.medina31@example.com',
        password: 'password123',
        phoneNumber: '123-456-7893',
        status: 'Active',
        location: { latitude: 40.7128, longitude: -74.006 },
        locationName: 'New York',
        address: '2828 Maple St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Runner',
        role: 'User',
        profession: 'Runner',
        ageRange: '40-45',
        country: 'USA',
        city: 'New York',
        state: 'NY',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Carol',
        lastName: 'Ortega',
        username: 'carolo32',
        nickname: 'Carrie',
        email: 'carol.ortega32@example.com',
        password: 'password123',
        phoneNumber: '234-567-8904',
        status: 'Active',
        location: { latitude: 34.0522, longitude: -118.2437 },
        locationName: 'Los Angeles',
        address: '2929 Birch St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Teacher',
        role: 'User',
        profession: 'Teacher',
        ageRange: '30-35',
        country: 'USA',
        city: 'Los Angeles',
        state: 'CA',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Joseph',
        lastName: 'Silva',
        username: 'josephs33',
        nickname: 'Joe',
        email: 'joseph.silva33@example.com',
        password: 'password123',
        phoneNumber: '345-678-9015',
        status: 'Active',
        location: { latitude: 51.5074, longitude: -0.1278 },
        locationName: 'London',
        address: '3030 Cedar St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Gardener',
        role: 'User',
        profession: 'Gardener',
        ageRange: '45-50',
        country: 'UK',
        city: 'London',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Virginia',
        lastName: 'Chavez',
        username: 'virginiac34',
        nickname: 'Ginny',
        email: 'virginia.chavez34@example.com',
        password: 'password123',
        phoneNumber: '456-789-0126',
        status: 'Active',
        location: { latitude: 48.8566, longitude: 2.3522 },
        locationName: 'Paris',
        address: '3131 Elm St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Poet',
        role: 'User',
        profession: 'Poet',
        ageRange: '20-25',
        country: 'France',
        city: 'Paris',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Larry',
        lastName: 'Estrada',
        username: 'larrye35',
        nickname: 'Lar',
        email: 'larry.estrada35@example.com',
        password: 'password123',
        phoneNumber: '567-890-1237',
        status: 'Active',
        location: { latitude: 35.6762, longitude: 139.6503 },
        locationName: 'Tokyo',
        address: '3232 Maple St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Chef',
        role: 'User',
        profession: 'Chef',
        ageRange: '35-40',
        country: 'Japan',
        city: 'Tokyo',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Louise',
        lastName: 'Rios',
        username: 'louisr36',
        nickname: 'Lou',
        email: 'louise.rios36@example.com',
        password: 'password123',
        phoneNumber: '678-901-2348',
        status: 'Active',
        location: { latitude: 37.7749, longitude: -122.4194 },
        locationName: 'San Francisco',
        address: '3333 Birch St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Nurse',
        role: 'User',
        profession: 'Nurse',
        ageRange: '25-30',
        country: 'USA',
        city: 'San Francisco',
        state: 'CA',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Mark',
        lastName: 'Alvarez',
        username: 'marka37',
        nickname: 'Marky',
        email: 'mark.alvarez37@example.com',
        password: 'password123',
        phoneNumber: '789-012-3459',
        status: 'Active',
        location: { latitude: 52.52, longitude: 13.405 },
        locationName: 'Berlin',
        address: '3434 Cedar St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Carpenter',
        role: 'User',
        profession: 'Carpenter',
        ageRange: '40-45',
        country: 'Germany',
        city: 'Berlin',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Karen',
        lastName: 'Vega',
        username: 'karenv38',
        nickname: 'Kari',
        email: 'karen.vega38@example.com',
        password: 'password123',
        phoneNumber: '890-123-4560',
        status: 'Active',
        location: { latitude: 55.7558, longitude: 37.6173 },
        locationName: 'Moscow',
        address: '3535 Elm St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Actress',
        role: 'User',
        profession: 'Actress',
        ageRange: '30-35',
        country: 'Russia',
        city: 'Moscow',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Donald',
        lastName: 'Maldonado',
        username: 'donaldm39',
        nickname: 'Donny',
        email: 'donald.maldonado39@example.com',
        password: 'password123',
        phoneNumber: '901-234-5671',
        status: 'Active',
        location: { latitude: -33.8688, longitude: 151.2093 },
        locationName: 'Sydney',
        address: '3636 Maple St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Fisherman',
        role: 'User',
        profession: 'Fisherman',
        ageRange: '35-40',
        country: 'Australia',
        city: 'Sydney',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Sharon',
        lastName: 'Castro',
        username: 'sharonc40',
        nickname: 'Shari',
        email: 'sharon.castro40@example.com',
        password: 'password123',
        phoneNumber: '012-345-6782',
        status: 'Active',
        location: { latitude: 19.4326, longitude: -99.1332 },
        locationName: 'Mexico City',
        address: '3737 Birch St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Dancer',
        role: 'User',
        profession: 'Dancer',
        ageRange: '25-30',
        country: 'Mexico',
        city: 'Mexico City',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Gary',
        lastName: 'Lara',
        username: 'garyl41',
        nickname: 'Garyy',
        email: 'gary.lara41@example.com',
        password: 'password123',
        phoneNumber: '123-456-7894',
        status: 'Active',
        location: { latitude: 40.7128, longitude: -74.006 },
        locationName: 'New York',
        address: '3838 Cedar St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Mechanic',
        role: 'User',
        profession: 'Mechanic',
        ageRange: '40-45',
        country: 'USA',
        city: 'New York',
        state: 'NY',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Deborah',
        lastName: 'Munoz',
        username: 'deborahm42',
        nickname: 'Deb',
        email: 'deborah.munoz42@example.com',
        password: 'password123',
        phoneNumber: '234-567-8905',
        status: 'Active',
        location: { latitude: 34.0522, longitude: -118.2437 },
        locationName: 'Los Angeles',
        address: '3939 Elm St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Therapist',
        role: 'User',
        profession: 'Therapist',
        ageRange: '30-35',
        country: 'USA',
        city: 'Los Angeles',
        state: 'CA',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Roger',
        lastName: 'Alvarado',
        username: 'rogera43',
        nickname: 'Rog',
        email: 'roger.alvarado43@example.com',
        password: 'password123',
        phoneNumber: '345-678-9016',
        status: 'Active',
        location: { latitude: 51.5074, longitude: -0.1278 },
        locationName: 'London',
        address: '4040 Maple St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Electrician',
        role: 'User',
        profession: 'Electrician',
        ageRange: '45-50',
        country: 'UK',
        city: 'London',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Diane',
        lastName: 'Blanco',
        username: 'dianeb44',
        nickname: 'Di',
        email: 'diane.blanco44@example.com',
        password: 'password123',
        phoneNumber: '456-789-0127',
        status: 'Active',
        location: { latitude: 48.8566, longitude: 2.3522 },
        locationName: 'Paris',
        address: '4141 Birch St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Florist',
        role: 'User',
        profession: 'Florist',
        ageRange: '20-25',
        country: 'France',
        city: 'Paris',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Keith',
        lastName: 'Colon',
        username: 'keithc45',
        nickname: 'Kev',
        email: 'keith.colon45@example.com',
        password: 'password123',
        phoneNumber: '567-890-1238',
        status: 'Active',
        location: { latitude: 35.6762, longitude: 139.6503 },
        locationName: 'Tokyo',
        address: '4242 Cedar St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Architect',
        role: 'User',
        profession: 'Architect',
        ageRange: '35-40',
        country: 'Japan',
        city: 'Tokyo',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Joyce',
        lastName: 'Salazar',
        username: 'joyces46',
        nickname: 'Joy',
        email: 'joyce.salazar46@example.com',
        password: 'password123',
        phoneNumber: '678-901-2349',
        status: 'Active',
        location: { latitude: 37.7749, longitude: -122.4194 },
        locationName: 'San Francisco',
        address: '4343 Elm St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Vet',
        role: 'User',
        profession: 'Veterinarian',
        ageRange: '25-30',
        country: 'USA',
        city: 'San Francisco',
        state: 'CA',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Jerry',
        lastName: 'Nunez',
        username: 'jerryn47',
        nickname: 'Jer',
        email: 'jerry.nunez47@example.com',
        password: 'password123',
        phoneNumber: '789-012-3450',
        status: 'Active',
        location: { latitude: 52.52, longitude: 13.405 },
        locationName: 'Berlin',
        address: '4444 Maple St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Plumber',
        role: 'User',
        profession: 'Plumber',
        ageRange: '40-45',
        country: 'Germany',
        city: 'Berlin',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Theresa',
        lastName: 'Valdez',
        username: 'theresav48',
        nickname: 'Tess',
        email: 'theresa.valdez48@example.com',
        password: 'password123',
        phoneNumber: '890-123-4561',
        status: 'Active',
        location: { latitude: 55.7558, longitude: 37.6173 },
        locationName: 'Moscow',
        address: '4545 Birch St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Model',
        role: 'User',
        profession: 'Model',
        ageRange: '30-35',
        country: 'Russia',
        city: 'Moscow',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
      {
        firstName: 'Terry',
        lastName: 'Juarez',
        username: 'terryj49',
        nickname: 'Ter',
        email: 'terry.juarez49@example.com',
        password: 'password123',
        phoneNumber: '901-234-5672',
        status: 'Active',
        location: { latitude: -33.8688, longitude: 151.2093 },
        locationName: 'Sydney',
        address: '4646 Cedar St',
        gender: 'Male',
        maritalStatus: 'Married',
        description: 'Pilot',
        role: 'User',
        profession: 'Pilot',
        ageRange: '35-40',
        country: 'Australia',
        city: 'Sydney',
        state: '',
        referredAs: 'Friend',
        isEmailVerified: true,
      },
      {
        firstName: 'Beverly',
        lastName: 'Tapia',
        username: 'beverlyt50',
        nickname: 'Bev',
        email: 'beverly.tapia50@example.com',
        password: 'password123',
        phoneNumber: '012-345-6783',
        status: 'Active',
        location: { latitude: 19.4326, longitude: -99.1332 },
        locationName: 'Mexico City',
        address: '4747 Elm St',
        gender: 'Female',
        maritalStatus: 'Single',
        description: 'Designer',
        role: 'User',
        profession: 'Designer',
        ageRange: '25-30',
        country: 'Mexico',
        city: 'Mexico City',
        state: '',
        referredAs: 'Colleague',
        isEmailVerified: true,
      },
    ];

    // Hash the password before saving users
    for (const user of usersData) {
      user.password = await hashPassword(user.password);
    }

    await User.deleteMany({});
    await User.insertMany(usersData);
    console.log('Users seeded successfully!');
  } catch (err) {
    console.error('Error seeding users:', err);
  }
};

// Connect to MongoDB
const connectToDatabase = async () => {
  try {
    const dbUrl = process.env.MONGODB_URL;
    if (!dbUrl) throw new Error('MONGODB_URL not set in environment variables');

    await mongoose.connect(dbUrl);
    console.log('Connected to MongoDB');
  } catch (err) {
    console.error('Error connecting to MongoDB:', err);
    process.exit(1); // Exit process with failure
  }
};

// Main function to seed the database
const seedDatabase = async () => {
  try {
    await connectToDatabase();
    await dropDatabase();
    await seedUsers();
    console.log('--------------> Database seeding completed <--------------');
  } catch (err) {
    console.error('Error seeding database:', err);
  } finally {
    mongoose.disconnect().then(() => console.log('Disconnected from MongoDB'));
  }
};

// Execute seeding
seedDatabase();
